id = "python-requirements"
name = "Python requirements and constraints"
version = "0.0.2"
schema_version = 1
authors = ["Gabriel Linder <linder.gabriel@gmail.com>"]
description = "Syntax highlighting for requirements.txt and constraints.txt files"
repository = "https://github.com/dargor/zed-python-requirements"

[grammars.requirements]
repository = "https://github.com/tree-sitter-grammars/tree-sitter-requirements"
commit = "caeb2ba854dea55931f76034978de1fd79362939"
